# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "dia1/" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "dia1/" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "dia2/" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "dia3/" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "dia4/" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "dia5/" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "dia6/" # Location of package manifests
    schedule:
      interval: "weekly"
